proc_noise:
  q: 1e1
  dq: 1e4
  pos: 1e-9
  stiff: 1e0
  rest: 1e-5
cov_init:
  q: 1e-1
  dq: 1e5
  pos: 1e-8
  stiff: 1e0
  rest: 5e-8
meas_noise:
  q: 1e-5
  tau_ext: 5e0
lb:
  imp_stiff: 1e-4
  imp_rest: -1.5
ub:
  imp_stiff: 400
  imp_rest: 1.5
