urdf_path: config/franka.urdf
ee_frame_name: fr3_link8
joint_names:
  - panda_joint1
  - panda_joint2
  - panda_joint3
  - panda_joint4
  - panda_joint5
  - panda_joint6
  - panda_joint7
visc_fric: 50
