proc_noise:
  q: 1e1
  dq: 1e4
  pos: 1e5
  stiff: 5e10
  rest: 1e5
cov_init:
  q: 1e-1
  dq: 1e5
  pos: 1.5e6
  stiff: 6e15
  rest: 1e6
meas_noise:
  q: 1e-1
  tau_ext: 1e1
lb:
  imp_stiff: 1e-4
  imp_rest: -1
ub:
  imp_stiff: 400
  imp_rest: 1