# For testing about the joint pose q=ones

modes:
  free: []
  point: [contact_1]
models:
  contact_1: # prefix all contacts with contact if they should be found by MPC solver in cost fn
    pos: [0, 0, 0]
    stiff: [4e3, 0, 0]
    rest: [-0.200, 0.180, 0.816]