# Print settings
ipopt.print_level: 0 # 0 to 5, 5 is most print info
print_time: false
verbose: false

# Termination conditions
ipopt.tol: 1.0e-05   # Tolerance on change in scaled obj fn
ipopt.constr_viol_tol: 5.0e-04
ipopt.max_cpu_time: 10.0
ipopt.max_iter: 50
ipopt.acceptable_constr_viol_tol: 5.0e-04
ipopt.acceptable_tol: 1.0e-5
ipopt.acceptable_iter: 5

ipopt.bound_relax_factor: 1.0e-04

ipopt.fixed_variable_treatment: 'make_parameter'

ipopt.mu_strategy: adaptive
ipopt.mu_oracle: probing

#ipopt.mu_strategy: monotone
#ipopt.mu_init: 0.1

ipopt.linear_solver: 'MUMPS' #'MUMPS' or 'MA86'
ipopt.ma57_automatic_scaling: 'no'

ipopt.warm_start_bound_frac: 1.0e-08
ipopt.warm_start_bound_push: 1.0e-08
ipopt.warm_start_init_point: 'yes'


