H: 20
dt: 0.04

vel_cost: 0.05
des_pose: [-0.1, 0.2, 0.5]
imp_cost: 0.1

# ICEM params
alpha_mu: 0.9   # tuning parameter for distribution smoothing over time
alpha_std: 0.7 
beta: 4.0       # noise tuning parameter
num_samples: 80 # number of samples for action trajectories --> same of number of filter particles
num_iter: 40    # number of iterations 
num_elites: 8   # number of elites to maintain

