H: 10
dt: 0.15

vel_cost: 0.05
des_pose: [0.1, 0.3, 0.5]
imp_cost: 0.005

# ICEM params
alpha: 0.8     # tuning parameter for distribution smoothing over time
beta: 4.0       # noise tuning parameter
num_samples: 80 # number of samples for action trajectories --> same of number of filter particles
num_iter: 40    # number of iterations 
num_elites: 8   # number of elites to maintain

