modes:
  free: []
  plane: [contact_1]
  hinge: [contact_1, contact_2]
models:
  contact_1: # plane
    pos: [0.135, -0.135, 0.16]
    stiff: [0, 0, 400]
    rest: [0.45, -0.43, -0.09]
  contact_2: # hinge
    pos:  [0.135, -0.135, 0.16]
    stiff: [400, 0, 0]
    rest: [0.30, -0.465, -0.09]
est_pars: []
#est_pars:
#  contact_1: rest
