H: 10
dt: 0.04

vel_cost: 0.05
des_pose: [0.4, -0.4, 0.26]

imp_cost: 0.0
max_imp_force: 25

force_cost: 5e-4
force_setpoint: 15

num_warmstart: 5

jit: false

# ICEM params
alpha_mu: 0.9  # tuning parameter for distribution smoothing over time
alpha_std: 0.5
beta: 4.0       # noise tuning parameter
num_samples: 80 # number of samples for action trajectories --> same of number of filter particles
num_iter: 120    # number of iterations 
num_elites: 16  # number of elites to maintain


