H: 15
dt: 0.04

vel_cost: 0.0

des_pose_mode:
  hinge: [0.38, -0.6, -0.15]

imp_cost: 0.05
max_imp_force: 30

force_cost: 2e-5
force_setpoint: 7

num_warmstart: 0

jit: false

# ICEM params
alpha_mu: 0.9  # tuning parameter for distribution smoothing over time
alpha_std: 0.5
beta: 4.0       # noise tuning parameter
num_samples: 80 # number of samples for action trajectories --> same of number of filter particles
num_iter: 120    # number of iterations 
num_elites: 16  # number of elites to maintain
